doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        host: '%env(string:key:host:json:DATABASE_CREDENTIALS)%'
        dbname: '%env(string:key:dbname:json:DATABASE_CREDENTIALS)%'
        port: '%env(string:key:port:json:DATABASE_CREDENTIALS)%'
        user: '%env(string:key:username:json:DATABASE_CREDENTIALS)%'
        password: '%env(string:key:password:json:DATABASE_CREDENTIALS)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
